# slicing + masques booléens.

In [4]:
import numpy as np

In [ ]:
a = np.array([1.2,2.5,3.2,1.8]) # createur de veteur  à partir dune liste de 4 élément

In [16]:
print(type(a)) # #type de la structure
print(a.dtype) # #type des données
print(a.ndim) # #nombre de dimensions
print(a.shape) # #nombre de lignes et col
print(a.size) # #nombre totale de valeurs


<class 'numpy.ndarray'>
float64
1
(4,)
4


In [17]:
a = np.array([1,2,4]) 
print(a.dtype) #int32

int64


In [18]:
a = np.array([1,2,4],dtype=float)
print(a.dtype) #float64
print(a)


float64
[1. 2. 4.]


In [ ]:
b = np.array([True,False,True,True], dtype=bool)
print(b)
a = np.array([{"Toto":(45,2000)},{"Tata":(34,1500)}])
print(a.dtype) #object

[ True False  True  True]
object


In [23]:
a = np.arange(start=0, stop=10)
# [0 1 2 3 4 5 6 7 8 9]
a
a = np.arange(0, 10, 2)
a

array([0, 2, 4, 6, 8])

v[debut : fin : pas]


v[:]   # ou print(v)
Le slicing [:] permet de sélectionner l’ensemble des valeurs.

In [24]:
a[:]

array([0, 2, 4, 6, 8])

In [ ]:
a[a.size -1] # Les indices négatifs permettent d’accéder à partir de la fin.”

np.int64(8)

In [27]:
a[1:3]  # “Le slicing NumPy est semi-ouvert : [start, stop[.”
a[-1]      # dernier
a[-3:]     # 3 derniers

array([4, 6, 8])

In [ ]:
b =np.flip(a) # Inversion
b

array([8, 6, 4, 2, 0])

| Expression             | Effet                |
| ---------------------- | -------------------- |
| `v > 0`                | masque booléen       |
| `v[v > 0]`             | filtrage             |
| `v[(v > 0) & (v < 5)]` | conditions multiples |
| `v[v == 0]`            | égalité              |
| `v[v != 0]`            | exclusion            |


In [31]:
v = np.array([1.2, 7.4, 4.2, 8.5, 6.3])
b = np.array([False, True, False, True, False], dtype=bool)
v[b] # indexer un array avec un masque booléen de même taille.
# [7.4  8.5]


array([7.4, 8.5])

In [33]:
v[v<7]  # v < 7 → crée un array de booléen et numpy selectionne les true

array([1.2, 4.2, 6.3])

In [39]:
v

array([1.2, 7.4, 4.2, 8.5, 6.3])

In [ ]:
v.max()
np.argmax(v) # Indice du maximum
v.sort()
np.argsort(v) # argsort pour réordonner d’autres variables selon un score.

array([0, 1, 2, 3, 4])

# elementwise

In [45]:
x = np.array([1.2, 1.3, 1.0])
y = np.array([2.1, 0.8, 1.3])


In [ ]:
x * y
# [2.52  1.04  1.3]  
# Les opérations NumPy sont vectorisées et s’effectuent élément par élément, 
# ce qui évite les boucles explicites et améliore les performances.

array([2.52, 1.04, 1.3 ])